# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 771, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.status = QtWidgets.QLabel(self.gridLayoutWidget)
        self.status.setTextFormat(QtCore.Qt.AutoText)
        self.status.setObjectName("status")
        self.gridLayout_2.addWidget(self.status, 1, 0, 1, 1)
        self.botao = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botao.setObjectName("botao")
        self.gridLayout_2.addWidget(self.botao, 2, 0, 1, 1)
        self.exibir_texto = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.exibir_texto.setObjectName("exibir_texto")
        self.gridLayout_2.addWidget(self.exibir_texto, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Teste PyQT5"))
        self.status.setText(_translate("MainWindow", "Botão não funcionou ou não apertado!"))
        self.botao.setText(_translate("MainWindow", "PushButton"))
